// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE8_Iy34e4F0Ov7t0FbC4qS6C-Bf79a-8',
    appId: '1:726543447047:web:4c626762cd1397e6ec66a2',
    messagingSenderId: '726543447047',
    projectId: 'yatharthfcm',
    authDomain: 'yatharthfcm.firebaseapp.com',
    storageBucket: 'yatharthfcm.firebasestorage.app',
    measurementId: 'G-93EBEF39FK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJDDZWoUxJGdSHO9KgbFggGs2fBcginrg',
    appId: '1:726543447047:android:8b9fd6d79422bc49ec66a2',
    messagingSenderId: '726543447047',
    projectId: 'yatharthfcm',
    storageBucket: 'yatharthfcm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiDMRT4qtxdfzsJpoZyN1z7j0JsgdSrZQ',
    appId: '1:726543447047:ios:8fea7b417f5efdcaec66a2',
    messagingSenderId: '726543447047',
    projectId: 'yatharthfcm',
    storageBucket: 'yatharthfcm.firebasestorage.app',
    iosBundleId: 'com.eams.attendanceApp',
  );
}
